Fix px4 error

diff --git a/docker/Dockerfile.unified b/docker/Dockerfile.unified
--- a/docker/Dockerfile.unified
+++ b/docker/Dockerfile.unified
@@ -71,7 +71,9 @@ USER root
 RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
     rosdep install --from-paths /sim_ws/src --rosdistro ${ROS_DISTRO} -y --ignore-src && \
     colcon build --symlink-install --event-handlers console_direct+
-RUN ls /sim_ws/install/lib/python3.10/site-packages/drone_msgs/msg/_drone_control_command.py || (echo 'ERROR: drone_msgs Python bindings not found!' && exit 1)
+RUN (ls /sim_ws/install/lib/python3.10/site-packages/drone_msgs/msg/_drone_control_command.py \
+  || ls /sim_ws/install/drone_msgs/local/lib/python3.10/dist-packages/drone_msgs/msg/_drone_control_command.py) \
+  || (echo 'ERROR: drone_msgs Python bindings not found!' && exit 1)
 
 # --- px4_msgsのPythonバインディングが存在するかチェック ---
 RUN ls /sim_ws/install/lib/python3.10/site-packages/px4_msgs || echo 'px4_msgs not found'
